// source: model/dynamicforkjointasklist.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var model_dynamicforkjointask_pb = require('../model/dynamicforkjointask_pb.js');
goog.object.extend(proto, model_dynamicforkjointask_pb);
goog.exportSymbol('proto.conductor.proto.DynamicForkJoinTaskList', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.conductor.proto.DynamicForkJoinTaskList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.conductor.proto.DynamicForkJoinTaskList.repeatedFields_, null);
};
goog.inherits(proto.conductor.proto.DynamicForkJoinTaskList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.conductor.proto.DynamicForkJoinTaskList.displayName = 'proto.conductor.proto.DynamicForkJoinTaskList';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.conductor.proto.DynamicForkJoinTaskList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.conductor.proto.DynamicForkJoinTaskList.prototype.toObject = function(opt_includeInstance) {
  return proto.conductor.proto.DynamicForkJoinTaskList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.conductor.proto.DynamicForkJoinTaskList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.conductor.proto.DynamicForkJoinTaskList.toObject = function(includeInstance, msg) {
  var f, obj = {
    dynamicTasksList: jspb.Message.toObjectList(msg.getDynamicTasksList(),
    model_dynamicforkjointask_pb.DynamicForkJoinTask.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.conductor.proto.DynamicForkJoinTaskList}
 */
proto.conductor.proto.DynamicForkJoinTaskList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.conductor.proto.DynamicForkJoinTaskList;
  return proto.conductor.proto.DynamicForkJoinTaskList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.conductor.proto.DynamicForkJoinTaskList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.conductor.proto.DynamicForkJoinTaskList}
 */
proto.conductor.proto.DynamicForkJoinTaskList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new model_dynamicforkjointask_pb.DynamicForkJoinTask;
      reader.readMessage(value,model_dynamicforkjointask_pb.DynamicForkJoinTask.deserializeBinaryFromReader);
      msg.addDynamicTasks(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.conductor.proto.DynamicForkJoinTaskList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.conductor.proto.DynamicForkJoinTaskList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.conductor.proto.DynamicForkJoinTaskList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.conductor.proto.DynamicForkJoinTaskList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDynamicTasksList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      model_dynamicforkjointask_pb.DynamicForkJoinTask.serializeBinaryToWriter
    );
  }
};


/**
 * repeated DynamicForkJoinTask dynamic_tasks = 1;
 * @return {!Array<!proto.conductor.proto.DynamicForkJoinTask>}
 */
proto.conductor.proto.DynamicForkJoinTaskList.prototype.getDynamicTasksList = function() {
  return /** @type{!Array<!proto.conductor.proto.DynamicForkJoinTask>} */ (
    jspb.Message.getRepeatedWrapperField(this, model_dynamicforkjointask_pb.DynamicForkJoinTask, 1));
};


/**
 * @param {!Array<!proto.conductor.proto.DynamicForkJoinTask>} value
 * @return {!proto.conductor.proto.DynamicForkJoinTaskList} returns this
*/
proto.conductor.proto.DynamicForkJoinTaskList.prototype.setDynamicTasksList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.conductor.proto.DynamicForkJoinTask=} opt_value
 * @param {number=} opt_index
 * @return {!proto.conductor.proto.DynamicForkJoinTask}
 */
proto.conductor.proto.DynamicForkJoinTaskList.prototype.addDynamicTasks = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.conductor.proto.DynamicForkJoinTask, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.conductor.proto.DynamicForkJoinTaskList} returns this
 */
proto.conductor.proto.DynamicForkJoinTaskList.prototype.clearDynamicTasksList = function() {
  return this.setDynamicTasksList([]);
};


goog.object.extend(exports, proto.conductor.proto);
