// source: model/startworkflowrequest.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var model_workflowdef_pb = require('../model/workflowdef_pb.js');
goog.object.extend(proto, model_workflowdef_pb);
var google_protobuf_struct_pb = require('google-protobuf/google/protobuf/struct_pb.js');
goog.object.extend(proto, google_protobuf_struct_pb);
goog.exportSymbol('proto.conductor.proto.StartWorkflowRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.conductor.proto.StartWorkflowRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.conductor.proto.StartWorkflowRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.conductor.proto.StartWorkflowRequest.displayName = 'proto.conductor.proto.StartWorkflowRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.conductor.proto.StartWorkflowRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.conductor.proto.StartWorkflowRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.conductor.proto.StartWorkflowRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.conductor.proto.StartWorkflowRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    version: jspb.Message.getFieldWithDefault(msg, 2, 0),
    correlationId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    inputMap: (f = msg.getInputMap()) ? f.toObject(includeInstance, proto.google.protobuf.Value.toObject) : [],
    taskToDomainMap: (f = msg.getTaskToDomainMap()) ? f.toObject(includeInstance, undefined) : [],
    workflowDef: (f = msg.getWorkflowDef()) && model_workflowdef_pb.WorkflowDef.toObject(includeInstance, f),
    externalInputPayloadStoragePath: jspb.Message.getFieldWithDefault(msg, 7, ""),
    priority: jspb.Message.getFieldWithDefault(msg, 8, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.conductor.proto.StartWorkflowRequest}
 */
proto.conductor.proto.StartWorkflowRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.conductor.proto.StartWorkflowRequest;
  return proto.conductor.proto.StartWorkflowRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.conductor.proto.StartWorkflowRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.conductor.proto.StartWorkflowRequest}
 */
proto.conductor.proto.StartWorkflowRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setVersion(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCorrelationId(value);
      break;
    case 4:
      var value = msg.getInputMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.google.protobuf.Value.deserializeBinaryFromReader, "", new proto.google.protobuf.Value());
         });
      break;
    case 5:
      var value = msg.getTaskToDomainMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 6:
      var value = new model_workflowdef_pb.WorkflowDef;
      reader.readMessage(value,model_workflowdef_pb.WorkflowDef.deserializeBinaryFromReader);
      msg.setWorkflowDef(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setExternalInputPayloadStoragePath(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPriority(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.conductor.proto.StartWorkflowRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.conductor.proto.StartWorkflowRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.conductor.proto.StartWorkflowRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.conductor.proto.StartWorkflowRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getVersion();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getCorrelationId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getInputMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(4, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.google.protobuf.Value.serializeBinaryToWriter);
  }
  f = message.getTaskToDomainMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(5, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getWorkflowDef();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      model_workflowdef_pb.WorkflowDef.serializeBinaryToWriter
    );
  }
  f = message.getExternalInputPayloadStoragePath();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getPriority();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.conductor.proto.StartWorkflowRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.conductor.proto.StartWorkflowRequest} returns this
 */
proto.conductor.proto.StartWorkflowRequest.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 version = 2;
 * @return {number}
 */
proto.conductor.proto.StartWorkflowRequest.prototype.getVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.conductor.proto.StartWorkflowRequest} returns this
 */
proto.conductor.proto.StartWorkflowRequest.prototype.setVersion = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string correlation_id = 3;
 * @return {string}
 */
proto.conductor.proto.StartWorkflowRequest.prototype.getCorrelationId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.conductor.proto.StartWorkflowRequest} returns this
 */
proto.conductor.proto.StartWorkflowRequest.prototype.setCorrelationId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * map<string, google.protobuf.Value> input = 4;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.google.protobuf.Value>}
 */
proto.conductor.proto.StartWorkflowRequest.prototype.getInputMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.google.protobuf.Value>} */ (
      jspb.Message.getMapField(this, 4, opt_noLazyCreate,
      proto.google.protobuf.Value));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.conductor.proto.StartWorkflowRequest} returns this
 */
proto.conductor.proto.StartWorkflowRequest.prototype.clearInputMap = function() {
  this.getInputMap().clear();
  return this;};


/**
 * map<string, string> task_to_domain = 5;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.conductor.proto.StartWorkflowRequest.prototype.getTaskToDomainMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 5, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.conductor.proto.StartWorkflowRequest} returns this
 */
proto.conductor.proto.StartWorkflowRequest.prototype.clearTaskToDomainMap = function() {
  this.getTaskToDomainMap().clear();
  return this;};


/**
 * optional WorkflowDef workflow_def = 6;
 * @return {?proto.conductor.proto.WorkflowDef}
 */
proto.conductor.proto.StartWorkflowRequest.prototype.getWorkflowDef = function() {
  return /** @type{?proto.conductor.proto.WorkflowDef} */ (
    jspb.Message.getWrapperField(this, model_workflowdef_pb.WorkflowDef, 6));
};


/**
 * @param {?proto.conductor.proto.WorkflowDef|undefined} value
 * @return {!proto.conductor.proto.StartWorkflowRequest} returns this
*/
proto.conductor.proto.StartWorkflowRequest.prototype.setWorkflowDef = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.conductor.proto.StartWorkflowRequest} returns this
 */
proto.conductor.proto.StartWorkflowRequest.prototype.clearWorkflowDef = function() {
  return this.setWorkflowDef(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.conductor.proto.StartWorkflowRequest.prototype.hasWorkflowDef = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string external_input_payload_storage_path = 7;
 * @return {string}
 */
proto.conductor.proto.StartWorkflowRequest.prototype.getExternalInputPayloadStoragePath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.conductor.proto.StartWorkflowRequest} returns this
 */
proto.conductor.proto.StartWorkflowRequest.prototype.setExternalInputPayloadStoragePath = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional int32 priority = 8;
 * @return {number}
 */
proto.conductor.proto.StartWorkflowRequest.prototype.getPriority = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.conductor.proto.StartWorkflowRequest} returns this
 */
proto.conductor.proto.StartWorkflowRequest.prototype.setPriority = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


goog.object.extend(exports, proto.conductor.proto);
