// source: model/workflow.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var model_workflowdef_pb = require('../model/workflowdef_pb.js');
goog.object.extend(proto, model_workflowdef_pb);
var model_task_pb = require('../model/task_pb.js');
goog.object.extend(proto, model_task_pb);
var google_protobuf_struct_pb = require('google-protobuf/google/protobuf/struct_pb.js');
goog.object.extend(proto, google_protobuf_struct_pb);
goog.exportSymbol('proto.conductor.proto.Workflow', null, global);
goog.exportSymbol('proto.conductor.proto.Workflow.WorkflowStatus', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.conductor.proto.Workflow = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.conductor.proto.Workflow.repeatedFields_, null);
};
goog.inherits(proto.conductor.proto.Workflow, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.conductor.proto.Workflow.displayName = 'proto.conductor.proto.Workflow';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.conductor.proto.Workflow.repeatedFields_ = [6,18];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.conductor.proto.Workflow.prototype.toObject = function(opt_includeInstance) {
  return proto.conductor.proto.Workflow.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.conductor.proto.Workflow} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.conductor.proto.Workflow.toObject = function(includeInstance, msg) {
  var f, obj = {
    status: jspb.Message.getFieldWithDefault(msg, 1, 0),
    endTime: jspb.Message.getFieldWithDefault(msg, 2, 0),
    workflowId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    parentWorkflowId: jspb.Message.getFieldWithDefault(msg, 4, ""),
    parentWorkflowTaskId: jspb.Message.getFieldWithDefault(msg, 5, ""),
    tasksList: jspb.Message.toObjectList(msg.getTasksList(),
    model_task_pb.Task.toObject, includeInstance),
    inputMap: (f = msg.getInputMap()) ? f.toObject(includeInstance, proto.google.protobuf.Value.toObject) : [],
    outputMap: (f = msg.getOutputMap()) ? f.toObject(includeInstance, proto.google.protobuf.Value.toObject) : [],
    correlationId: jspb.Message.getFieldWithDefault(msg, 12, ""),
    reRunFromWorkflowId: jspb.Message.getFieldWithDefault(msg, 13, ""),
    reasonForIncompletion: jspb.Message.getFieldWithDefault(msg, 14, ""),
    event: jspb.Message.getFieldWithDefault(msg, 16, ""),
    taskToDomainMap: (f = msg.getTaskToDomainMap()) ? f.toObject(includeInstance, undefined) : [],
    failedReferenceTaskNamesList: (f = jspb.Message.getRepeatedField(msg, 18)) == null ? undefined : f,
    workflowDefinition: (f = msg.getWorkflowDefinition()) && model_workflowdef_pb.WorkflowDef.toObject(includeInstance, f),
    externalInputPayloadStoragePath: jspb.Message.getFieldWithDefault(msg, 20, ""),
    externalOutputPayloadStoragePath: jspb.Message.getFieldWithDefault(msg, 21, ""),
    priority: jspb.Message.getFieldWithDefault(msg, 22, 0),
    variablesMap: (f = msg.getVariablesMap()) ? f.toObject(includeInstance, proto.google.protobuf.Value.toObject) : [],
    lastRetriedTime: jspb.Message.getFieldWithDefault(msg, 24, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.conductor.proto.Workflow}
 */
proto.conductor.proto.Workflow.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.conductor.proto.Workflow;
  return proto.conductor.proto.Workflow.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.conductor.proto.Workflow} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.conductor.proto.Workflow}
 */
proto.conductor.proto.Workflow.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.conductor.proto.Workflow.WorkflowStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setEndTime(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setWorkflowId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setParentWorkflowId(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setParentWorkflowTaskId(value);
      break;
    case 6:
      var value = new model_task_pb.Task;
      reader.readMessage(value,model_task_pb.Task.deserializeBinaryFromReader);
      msg.addTasks(value);
      break;
    case 8:
      var value = msg.getInputMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.google.protobuf.Value.deserializeBinaryFromReader, "", new proto.google.protobuf.Value());
         });
      break;
    case 9:
      var value = msg.getOutputMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.google.protobuf.Value.deserializeBinaryFromReader, "", new proto.google.protobuf.Value());
         });
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setCorrelationId(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setReRunFromWorkflowId(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setReasonForIncompletion(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setEvent(value);
      break;
    case 17:
      var value = msg.getTaskToDomainMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 18:
      var value = /** @type {string} */ (reader.readString());
      msg.addFailedReferenceTaskNames(value);
      break;
    case 19:
      var value = new model_workflowdef_pb.WorkflowDef;
      reader.readMessage(value,model_workflowdef_pb.WorkflowDef.deserializeBinaryFromReader);
      msg.setWorkflowDefinition(value);
      break;
    case 20:
      var value = /** @type {string} */ (reader.readString());
      msg.setExternalInputPayloadStoragePath(value);
      break;
    case 21:
      var value = /** @type {string} */ (reader.readString());
      msg.setExternalOutputPayloadStoragePath(value);
      break;
    case 22:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPriority(value);
      break;
    case 23:
      var value = msg.getVariablesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.google.protobuf.Value.deserializeBinaryFromReader, "", new proto.google.protobuf.Value());
         });
      break;
    case 24:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLastRetriedTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.conductor.proto.Workflow.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.conductor.proto.Workflow.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.conductor.proto.Workflow} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.conductor.proto.Workflow.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getEndTime();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getWorkflowId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getParentWorkflowId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getParentWorkflowTaskId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getTasksList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      model_task_pb.Task.serializeBinaryToWriter
    );
  }
  f = message.getInputMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(8, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.google.protobuf.Value.serializeBinaryToWriter);
  }
  f = message.getOutputMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(9, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.google.protobuf.Value.serializeBinaryToWriter);
  }
  f = message.getCorrelationId();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getReRunFromWorkflowId();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getReasonForIncompletion();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getEvent();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
  f = message.getTaskToDomainMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(17, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getFailedReferenceTaskNamesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      18,
      f
    );
  }
  f = message.getWorkflowDefinition();
  if (f != null) {
    writer.writeMessage(
      19,
      f,
      model_workflowdef_pb.WorkflowDef.serializeBinaryToWriter
    );
  }
  f = message.getExternalInputPayloadStoragePath();
  if (f.length > 0) {
    writer.writeString(
      20,
      f
    );
  }
  f = message.getExternalOutputPayloadStoragePath();
  if (f.length > 0) {
    writer.writeString(
      21,
      f
    );
  }
  f = message.getPriority();
  if (f !== 0) {
    writer.writeInt32(
      22,
      f
    );
  }
  f = message.getVariablesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(23, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.google.protobuf.Value.serializeBinaryToWriter);
  }
  f = message.getLastRetriedTime();
  if (f !== 0) {
    writer.writeInt64(
      24,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.conductor.proto.Workflow.WorkflowStatus = {
  RUNNING: 0,
  COMPLETED: 1,
  FAILED: 2,
  TIMED_OUT: 3,
  TERMINATED: 4,
  PAUSED: 5
};

/**
 * optional WorkflowStatus status = 1;
 * @return {!proto.conductor.proto.Workflow.WorkflowStatus}
 */
proto.conductor.proto.Workflow.prototype.getStatus = function() {
  return /** @type {!proto.conductor.proto.Workflow.WorkflowStatus} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.conductor.proto.Workflow.WorkflowStatus} value
 * @return {!proto.conductor.proto.Workflow} returns this
 */
proto.conductor.proto.Workflow.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional int64 end_time = 2;
 * @return {number}
 */
proto.conductor.proto.Workflow.prototype.getEndTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.conductor.proto.Workflow} returns this
 */
proto.conductor.proto.Workflow.prototype.setEndTime = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string workflow_id = 3;
 * @return {string}
 */
proto.conductor.proto.Workflow.prototype.getWorkflowId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.conductor.proto.Workflow} returns this
 */
proto.conductor.proto.Workflow.prototype.setWorkflowId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string parent_workflow_id = 4;
 * @return {string}
 */
proto.conductor.proto.Workflow.prototype.getParentWorkflowId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.conductor.proto.Workflow} returns this
 */
proto.conductor.proto.Workflow.prototype.setParentWorkflowId = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string parent_workflow_task_id = 5;
 * @return {string}
 */
proto.conductor.proto.Workflow.prototype.getParentWorkflowTaskId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.conductor.proto.Workflow} returns this
 */
proto.conductor.proto.Workflow.prototype.setParentWorkflowTaskId = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * repeated Task tasks = 6;
 * @return {!Array<!proto.conductor.proto.Task>}
 */
proto.conductor.proto.Workflow.prototype.getTasksList = function() {
  return /** @type{!Array<!proto.conductor.proto.Task>} */ (
    jspb.Message.getRepeatedWrapperField(this, model_task_pb.Task, 6));
};


/**
 * @param {!Array<!proto.conductor.proto.Task>} value
 * @return {!proto.conductor.proto.Workflow} returns this
*/
proto.conductor.proto.Workflow.prototype.setTasksList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.conductor.proto.Task=} opt_value
 * @param {number=} opt_index
 * @return {!proto.conductor.proto.Task}
 */
proto.conductor.proto.Workflow.prototype.addTasks = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.conductor.proto.Task, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.conductor.proto.Workflow} returns this
 */
proto.conductor.proto.Workflow.prototype.clearTasksList = function() {
  return this.setTasksList([]);
};


/**
 * map<string, google.protobuf.Value> input = 8;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.google.protobuf.Value>}
 */
proto.conductor.proto.Workflow.prototype.getInputMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.google.protobuf.Value>} */ (
      jspb.Message.getMapField(this, 8, opt_noLazyCreate,
      proto.google.protobuf.Value));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.conductor.proto.Workflow} returns this
 */
proto.conductor.proto.Workflow.prototype.clearInputMap = function() {
  this.getInputMap().clear();
  return this;};


/**
 * map<string, google.protobuf.Value> output = 9;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.google.protobuf.Value>}
 */
proto.conductor.proto.Workflow.prototype.getOutputMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.google.protobuf.Value>} */ (
      jspb.Message.getMapField(this, 9, opt_noLazyCreate,
      proto.google.protobuf.Value));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.conductor.proto.Workflow} returns this
 */
proto.conductor.proto.Workflow.prototype.clearOutputMap = function() {
  this.getOutputMap().clear();
  return this;};


/**
 * optional string correlation_id = 12;
 * @return {string}
 */
proto.conductor.proto.Workflow.prototype.getCorrelationId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.conductor.proto.Workflow} returns this
 */
proto.conductor.proto.Workflow.prototype.setCorrelationId = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional string re_run_from_workflow_id = 13;
 * @return {string}
 */
proto.conductor.proto.Workflow.prototype.getReRunFromWorkflowId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.conductor.proto.Workflow} returns this
 */
proto.conductor.proto.Workflow.prototype.setReRunFromWorkflowId = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional string reason_for_incompletion = 14;
 * @return {string}
 */
proto.conductor.proto.Workflow.prototype.getReasonForIncompletion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.conductor.proto.Workflow} returns this
 */
proto.conductor.proto.Workflow.prototype.setReasonForIncompletion = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * optional string event = 16;
 * @return {string}
 */
proto.conductor.proto.Workflow.prototype.getEvent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/**
 * @param {string} value
 * @return {!proto.conductor.proto.Workflow} returns this
 */
proto.conductor.proto.Workflow.prototype.setEvent = function(value) {
  return jspb.Message.setProto3StringField(this, 16, value);
};


/**
 * map<string, string> task_to_domain = 17;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.conductor.proto.Workflow.prototype.getTaskToDomainMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 17, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.conductor.proto.Workflow} returns this
 */
proto.conductor.proto.Workflow.prototype.clearTaskToDomainMap = function() {
  this.getTaskToDomainMap().clear();
  return this;};


/**
 * repeated string failed_reference_task_names = 18;
 * @return {!Array<string>}
 */
proto.conductor.proto.Workflow.prototype.getFailedReferenceTaskNamesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 18));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.conductor.proto.Workflow} returns this
 */
proto.conductor.proto.Workflow.prototype.setFailedReferenceTaskNamesList = function(value) {
  return jspb.Message.setField(this, 18, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.conductor.proto.Workflow} returns this
 */
proto.conductor.proto.Workflow.prototype.addFailedReferenceTaskNames = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 18, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.conductor.proto.Workflow} returns this
 */
proto.conductor.proto.Workflow.prototype.clearFailedReferenceTaskNamesList = function() {
  return this.setFailedReferenceTaskNamesList([]);
};


/**
 * optional WorkflowDef workflow_definition = 19;
 * @return {?proto.conductor.proto.WorkflowDef}
 */
proto.conductor.proto.Workflow.prototype.getWorkflowDefinition = function() {
  return /** @type{?proto.conductor.proto.WorkflowDef} */ (
    jspb.Message.getWrapperField(this, model_workflowdef_pb.WorkflowDef, 19));
};


/**
 * @param {?proto.conductor.proto.WorkflowDef|undefined} value
 * @return {!proto.conductor.proto.Workflow} returns this
*/
proto.conductor.proto.Workflow.prototype.setWorkflowDefinition = function(value) {
  return jspb.Message.setWrapperField(this, 19, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.conductor.proto.Workflow} returns this
 */
proto.conductor.proto.Workflow.prototype.clearWorkflowDefinition = function() {
  return this.setWorkflowDefinition(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.conductor.proto.Workflow.prototype.hasWorkflowDefinition = function() {
  return jspb.Message.getField(this, 19) != null;
};


/**
 * optional string external_input_payload_storage_path = 20;
 * @return {string}
 */
proto.conductor.proto.Workflow.prototype.getExternalInputPayloadStoragePath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 20, ""));
};


/**
 * @param {string} value
 * @return {!proto.conductor.proto.Workflow} returns this
 */
proto.conductor.proto.Workflow.prototype.setExternalInputPayloadStoragePath = function(value) {
  return jspb.Message.setProto3StringField(this, 20, value);
};


/**
 * optional string external_output_payload_storage_path = 21;
 * @return {string}
 */
proto.conductor.proto.Workflow.prototype.getExternalOutputPayloadStoragePath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 21, ""));
};


/**
 * @param {string} value
 * @return {!proto.conductor.proto.Workflow} returns this
 */
proto.conductor.proto.Workflow.prototype.setExternalOutputPayloadStoragePath = function(value) {
  return jspb.Message.setProto3StringField(this, 21, value);
};


/**
 * optional int32 priority = 22;
 * @return {number}
 */
proto.conductor.proto.Workflow.prototype.getPriority = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 22, 0));
};


/**
 * @param {number} value
 * @return {!proto.conductor.proto.Workflow} returns this
 */
proto.conductor.proto.Workflow.prototype.setPriority = function(value) {
  return jspb.Message.setProto3IntField(this, 22, value);
};


/**
 * map<string, google.protobuf.Value> variables = 23;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.google.protobuf.Value>}
 */
proto.conductor.proto.Workflow.prototype.getVariablesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.google.protobuf.Value>} */ (
      jspb.Message.getMapField(this, 23, opt_noLazyCreate,
      proto.google.protobuf.Value));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.conductor.proto.Workflow} returns this
 */
proto.conductor.proto.Workflow.prototype.clearVariablesMap = function() {
  this.getVariablesMap().clear();
  return this;};


/**
 * optional int64 last_retried_time = 24;
 * @return {number}
 */
proto.conductor.proto.Workflow.prototype.getLastRetriedTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 24, 0));
};


/**
 * @param {number} value
 * @return {!proto.conductor.proto.Workflow} returns this
 */
proto.conductor.proto.Workflow.prototype.setLastRetriedTime = function(value) {
  return jspb.Message.setProto3IntField(this, 24, value);
};


goog.object.extend(exports, proto.conductor.proto);
