// source: model/workflowsummary.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var model_workflow_pb = require('../model/workflow_pb.js');
goog.object.extend(proto, model_workflow_pb);
goog.exportSymbol('proto.conductor.proto.WorkflowSummary', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.conductor.proto.WorkflowSummary = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.conductor.proto.WorkflowSummary, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.conductor.proto.WorkflowSummary.displayName = 'proto.conductor.proto.WorkflowSummary';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.conductor.proto.WorkflowSummary.prototype.toObject = function(opt_includeInstance) {
  return proto.conductor.proto.WorkflowSummary.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.conductor.proto.WorkflowSummary} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.conductor.proto.WorkflowSummary.toObject = function(includeInstance, msg) {
  var f, obj = {
    workflowType: jspb.Message.getFieldWithDefault(msg, 1, ""),
    version: jspb.Message.getFieldWithDefault(msg, 2, 0),
    workflowId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    correlationId: jspb.Message.getFieldWithDefault(msg, 4, ""),
    startTime: jspb.Message.getFieldWithDefault(msg, 5, ""),
    updateTime: jspb.Message.getFieldWithDefault(msg, 6, ""),
    endTime: jspb.Message.getFieldWithDefault(msg, 7, ""),
    status: jspb.Message.getFieldWithDefault(msg, 8, 0),
    input: jspb.Message.getFieldWithDefault(msg, 9, ""),
    output: jspb.Message.getFieldWithDefault(msg, 10, ""),
    reasonForIncompletion: jspb.Message.getFieldWithDefault(msg, 11, ""),
    executionTime: jspb.Message.getFieldWithDefault(msg, 12, 0),
    event: jspb.Message.getFieldWithDefault(msg, 13, ""),
    failedReferenceTaskNames: jspb.Message.getFieldWithDefault(msg, 14, ""),
    externalInputPayloadStoragePath: jspb.Message.getFieldWithDefault(msg, 15, ""),
    externalOutputPayloadStoragePath: jspb.Message.getFieldWithDefault(msg, 16, ""),
    priority: jspb.Message.getFieldWithDefault(msg, 17, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.conductor.proto.WorkflowSummary}
 */
proto.conductor.proto.WorkflowSummary.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.conductor.proto.WorkflowSummary;
  return proto.conductor.proto.WorkflowSummary.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.conductor.proto.WorkflowSummary} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.conductor.proto.WorkflowSummary}
 */
proto.conductor.proto.WorkflowSummary.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setWorkflowType(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setVersion(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setWorkflowId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setCorrelationId(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setStartTime(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setUpdateTime(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setEndTime(value);
      break;
    case 8:
      var value = /** @type {!proto.conductor.proto.Workflow.WorkflowStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setInput(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setOutput(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setReasonForIncompletion(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setExecutionTime(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setEvent(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setFailedReferenceTaskNames(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setExternalInputPayloadStoragePath(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setExternalOutputPayloadStoragePath(value);
      break;
    case 17:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPriority(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.conductor.proto.WorkflowSummary.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.conductor.proto.WorkflowSummary.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.conductor.proto.WorkflowSummary} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.conductor.proto.WorkflowSummary.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWorkflowType();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getVersion();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getWorkflowId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getCorrelationId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getStartTime();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getUpdateTime();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getEndTime();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      8,
      f
    );
  }
  f = message.getInput();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getOutput();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getReasonForIncompletion();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getExecutionTime();
  if (f !== 0) {
    writer.writeInt64(
      12,
      f
    );
  }
  f = message.getEvent();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getFailedReferenceTaskNames();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getExternalInputPayloadStoragePath();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
  f = message.getExternalOutputPayloadStoragePath();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
  f = message.getPriority();
  if (f !== 0) {
    writer.writeInt32(
      17,
      f
    );
  }
};


/**
 * optional string workflow_type = 1;
 * @return {string}
 */
proto.conductor.proto.WorkflowSummary.prototype.getWorkflowType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.conductor.proto.WorkflowSummary} returns this
 */
proto.conductor.proto.WorkflowSummary.prototype.setWorkflowType = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 version = 2;
 * @return {number}
 */
proto.conductor.proto.WorkflowSummary.prototype.getVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.conductor.proto.WorkflowSummary} returns this
 */
proto.conductor.proto.WorkflowSummary.prototype.setVersion = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string workflow_id = 3;
 * @return {string}
 */
proto.conductor.proto.WorkflowSummary.prototype.getWorkflowId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.conductor.proto.WorkflowSummary} returns this
 */
proto.conductor.proto.WorkflowSummary.prototype.setWorkflowId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string correlation_id = 4;
 * @return {string}
 */
proto.conductor.proto.WorkflowSummary.prototype.getCorrelationId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.conductor.proto.WorkflowSummary} returns this
 */
proto.conductor.proto.WorkflowSummary.prototype.setCorrelationId = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string start_time = 5;
 * @return {string}
 */
proto.conductor.proto.WorkflowSummary.prototype.getStartTime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.conductor.proto.WorkflowSummary} returns this
 */
proto.conductor.proto.WorkflowSummary.prototype.setStartTime = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string update_time = 6;
 * @return {string}
 */
proto.conductor.proto.WorkflowSummary.prototype.getUpdateTime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.conductor.proto.WorkflowSummary} returns this
 */
proto.conductor.proto.WorkflowSummary.prototype.setUpdateTime = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string end_time = 7;
 * @return {string}
 */
proto.conductor.proto.WorkflowSummary.prototype.getEndTime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.conductor.proto.WorkflowSummary} returns this
 */
proto.conductor.proto.WorkflowSummary.prototype.setEndTime = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional Workflow.WorkflowStatus status = 8;
 * @return {!proto.conductor.proto.Workflow.WorkflowStatus}
 */
proto.conductor.proto.WorkflowSummary.prototype.getStatus = function() {
  return /** @type {!proto.conductor.proto.Workflow.WorkflowStatus} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {!proto.conductor.proto.Workflow.WorkflowStatus} value
 * @return {!proto.conductor.proto.WorkflowSummary} returns this
 */
proto.conductor.proto.WorkflowSummary.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 8, value);
};


/**
 * optional string input = 9;
 * @return {string}
 */
proto.conductor.proto.WorkflowSummary.prototype.getInput = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.conductor.proto.WorkflowSummary} returns this
 */
proto.conductor.proto.WorkflowSummary.prototype.setInput = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string output = 10;
 * @return {string}
 */
proto.conductor.proto.WorkflowSummary.prototype.getOutput = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.conductor.proto.WorkflowSummary} returns this
 */
proto.conductor.proto.WorkflowSummary.prototype.setOutput = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string reason_for_incompletion = 11;
 * @return {string}
 */
proto.conductor.proto.WorkflowSummary.prototype.getReasonForIncompletion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.conductor.proto.WorkflowSummary} returns this
 */
proto.conductor.proto.WorkflowSummary.prototype.setReasonForIncompletion = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional int64 execution_time = 12;
 * @return {number}
 */
proto.conductor.proto.WorkflowSummary.prototype.getExecutionTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.conductor.proto.WorkflowSummary} returns this
 */
proto.conductor.proto.WorkflowSummary.prototype.setExecutionTime = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional string event = 13;
 * @return {string}
 */
proto.conductor.proto.WorkflowSummary.prototype.getEvent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.conductor.proto.WorkflowSummary} returns this
 */
proto.conductor.proto.WorkflowSummary.prototype.setEvent = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional string failed_reference_task_names = 14;
 * @return {string}
 */
proto.conductor.proto.WorkflowSummary.prototype.getFailedReferenceTaskNames = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.conductor.proto.WorkflowSummary} returns this
 */
proto.conductor.proto.WorkflowSummary.prototype.setFailedReferenceTaskNames = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * optional string external_input_payload_storage_path = 15;
 * @return {string}
 */
proto.conductor.proto.WorkflowSummary.prototype.getExternalInputPayloadStoragePath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/**
 * @param {string} value
 * @return {!proto.conductor.proto.WorkflowSummary} returns this
 */
proto.conductor.proto.WorkflowSummary.prototype.setExternalInputPayloadStoragePath = function(value) {
  return jspb.Message.setProto3StringField(this, 15, value);
};


/**
 * optional string external_output_payload_storage_path = 16;
 * @return {string}
 */
proto.conductor.proto.WorkflowSummary.prototype.getExternalOutputPayloadStoragePath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/**
 * @param {string} value
 * @return {!proto.conductor.proto.WorkflowSummary} returns this
 */
proto.conductor.proto.WorkflowSummary.prototype.setExternalOutputPayloadStoragePath = function(value) {
  return jspb.Message.setProto3StringField(this, 16, value);
};


/**
 * optional int32 priority = 17;
 * @return {number}
 */
proto.conductor.proto.WorkflowSummary.prototype.getPriority = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 17, 0));
};


/**
 * @param {number} value
 * @return {!proto.conductor.proto.WorkflowSummary} returns this
 */
proto.conductor.proto.WorkflowSummary.prototype.setPriority = function(value) {
  return jspb.Message.setProto3IntField(this, 17, value);
};


goog.object.extend(exports, proto.conductor.proto);
