// source: model/workflowdef.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var model_workflowtask_pb = require('../model/workflowtask_pb.js');
goog.object.extend(proto, model_workflowtask_pb);
var google_protobuf_struct_pb = require('google-protobuf/google/protobuf/struct_pb.js');
goog.object.extend(proto, google_protobuf_struct_pb);
goog.exportSymbol('proto.conductor.proto.WorkflowDef', null, global);
goog.exportSymbol('proto.conductor.proto.WorkflowDef.TimeoutPolicy', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.conductor.proto.WorkflowDef = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.conductor.proto.WorkflowDef.repeatedFields_, null);
};
goog.inherits(proto.conductor.proto.WorkflowDef, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.conductor.proto.WorkflowDef.displayName = 'proto.conductor.proto.WorkflowDef';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.conductor.proto.WorkflowDef.repeatedFields_ = [4,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.conductor.proto.WorkflowDef.prototype.toObject = function(opt_includeInstance) {
  return proto.conductor.proto.WorkflowDef.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.conductor.proto.WorkflowDef} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.conductor.proto.WorkflowDef.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    description: jspb.Message.getFieldWithDefault(msg, 2, ""),
    version: jspb.Message.getFieldWithDefault(msg, 3, 0),
    tasksList: jspb.Message.toObjectList(msg.getTasksList(),
    model_workflowtask_pb.WorkflowTask.toObject, includeInstance),
    inputParametersList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f,
    outputParametersMap: (f = msg.getOutputParametersMap()) ? f.toObject(includeInstance, proto.google.protobuf.Value.toObject) : [],
    failureWorkflow: jspb.Message.getFieldWithDefault(msg, 7, ""),
    schemaVersion: jspb.Message.getFieldWithDefault(msg, 8, 0),
    restartable: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
    workflowStatusListenerEnabled: jspb.Message.getBooleanFieldWithDefault(msg, 10, false),
    ownerEmail: jspb.Message.getFieldWithDefault(msg, 11, ""),
    timeoutPolicy: jspb.Message.getFieldWithDefault(msg, 12, 0),
    timeoutSeconds: jspb.Message.getFieldWithDefault(msg, 13, 0),
    variablesMap: (f = msg.getVariablesMap()) ? f.toObject(includeInstance, proto.google.protobuf.Value.toObject) : [],
    inputTemplateMap: (f = msg.getInputTemplateMap()) ? f.toObject(includeInstance, proto.google.protobuf.Value.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.conductor.proto.WorkflowDef}
 */
proto.conductor.proto.WorkflowDef.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.conductor.proto.WorkflowDef;
  return proto.conductor.proto.WorkflowDef.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.conductor.proto.WorkflowDef} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.conductor.proto.WorkflowDef}
 */
proto.conductor.proto.WorkflowDef.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setVersion(value);
      break;
    case 4:
      var value = new model_workflowtask_pb.WorkflowTask;
      reader.readMessage(value,model_workflowtask_pb.WorkflowTask.deserializeBinaryFromReader);
      msg.addTasks(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addInputParameters(value);
      break;
    case 6:
      var value = msg.getOutputParametersMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.google.protobuf.Value.deserializeBinaryFromReader, "", new proto.google.protobuf.Value());
         });
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setFailureWorkflow(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSchemaVersion(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRestartable(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setWorkflowStatusListenerEnabled(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setOwnerEmail(value);
      break;
    case 12:
      var value = /** @type {!proto.conductor.proto.WorkflowDef.TimeoutPolicy} */ (reader.readEnum());
      msg.setTimeoutPolicy(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimeoutSeconds(value);
      break;
    case 14:
      var value = msg.getVariablesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.google.protobuf.Value.deserializeBinaryFromReader, "", new proto.google.protobuf.Value());
         });
      break;
    case 15:
      var value = msg.getInputTemplateMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.google.protobuf.Value.deserializeBinaryFromReader, "", new proto.google.protobuf.Value());
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.conductor.proto.WorkflowDef.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.conductor.proto.WorkflowDef.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.conductor.proto.WorkflowDef} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.conductor.proto.WorkflowDef.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getVersion();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getTasksList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      model_workflowtask_pb.WorkflowTask.serializeBinaryToWriter
    );
  }
  f = message.getInputParametersList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
  f = message.getOutputParametersMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(6, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.google.protobuf.Value.serializeBinaryToWriter);
  }
  f = message.getFailureWorkflow();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getSchemaVersion();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = message.getRestartable();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
  f = message.getWorkflowStatusListenerEnabled();
  if (f) {
    writer.writeBool(
      10,
      f
    );
  }
  f = message.getOwnerEmail();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getTimeoutPolicy();
  if (f !== 0.0) {
    writer.writeEnum(
      12,
      f
    );
  }
  f = message.getTimeoutSeconds();
  if (f !== 0) {
    writer.writeInt64(
      13,
      f
    );
  }
  f = message.getVariablesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(14, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.google.protobuf.Value.serializeBinaryToWriter);
  }
  f = message.getInputTemplateMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(15, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.google.protobuf.Value.serializeBinaryToWriter);
  }
};


/**
 * @enum {number}
 */
proto.conductor.proto.WorkflowDef.TimeoutPolicy = {
  TIME_OUT_WF: 0,
  ALERT_ONLY: 1
};

/**
 * optional string name = 1;
 * @return {string}
 */
proto.conductor.proto.WorkflowDef.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.conductor.proto.WorkflowDef} returns this
 */
proto.conductor.proto.WorkflowDef.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string description = 2;
 * @return {string}
 */
proto.conductor.proto.WorkflowDef.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.conductor.proto.WorkflowDef} returns this
 */
proto.conductor.proto.WorkflowDef.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 version = 3;
 * @return {number}
 */
proto.conductor.proto.WorkflowDef.prototype.getVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.conductor.proto.WorkflowDef} returns this
 */
proto.conductor.proto.WorkflowDef.prototype.setVersion = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * repeated WorkflowTask tasks = 4;
 * @return {!Array<!proto.conductor.proto.WorkflowTask>}
 */
proto.conductor.proto.WorkflowDef.prototype.getTasksList = function() {
  return /** @type{!Array<!proto.conductor.proto.WorkflowTask>} */ (
    jspb.Message.getRepeatedWrapperField(this, model_workflowtask_pb.WorkflowTask, 4));
};


/**
 * @param {!Array<!proto.conductor.proto.WorkflowTask>} value
 * @return {!proto.conductor.proto.WorkflowDef} returns this
*/
proto.conductor.proto.WorkflowDef.prototype.setTasksList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.conductor.proto.WorkflowTask=} opt_value
 * @param {number=} opt_index
 * @return {!proto.conductor.proto.WorkflowTask}
 */
proto.conductor.proto.WorkflowDef.prototype.addTasks = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.conductor.proto.WorkflowTask, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.conductor.proto.WorkflowDef} returns this
 */
proto.conductor.proto.WorkflowDef.prototype.clearTasksList = function() {
  return this.setTasksList([]);
};


/**
 * repeated string input_parameters = 5;
 * @return {!Array<string>}
 */
proto.conductor.proto.WorkflowDef.prototype.getInputParametersList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.conductor.proto.WorkflowDef} returns this
 */
proto.conductor.proto.WorkflowDef.prototype.setInputParametersList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.conductor.proto.WorkflowDef} returns this
 */
proto.conductor.proto.WorkflowDef.prototype.addInputParameters = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.conductor.proto.WorkflowDef} returns this
 */
proto.conductor.proto.WorkflowDef.prototype.clearInputParametersList = function() {
  return this.setInputParametersList([]);
};


/**
 * map<string, google.protobuf.Value> output_parameters = 6;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.google.protobuf.Value>}
 */
proto.conductor.proto.WorkflowDef.prototype.getOutputParametersMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.google.protobuf.Value>} */ (
      jspb.Message.getMapField(this, 6, opt_noLazyCreate,
      proto.google.protobuf.Value));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.conductor.proto.WorkflowDef} returns this
 */
proto.conductor.proto.WorkflowDef.prototype.clearOutputParametersMap = function() {
  this.getOutputParametersMap().clear();
  return this;};


/**
 * optional string failure_workflow = 7;
 * @return {string}
 */
proto.conductor.proto.WorkflowDef.prototype.getFailureWorkflow = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.conductor.proto.WorkflowDef} returns this
 */
proto.conductor.proto.WorkflowDef.prototype.setFailureWorkflow = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional int32 schema_version = 8;
 * @return {number}
 */
proto.conductor.proto.WorkflowDef.prototype.getSchemaVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.conductor.proto.WorkflowDef} returns this
 */
proto.conductor.proto.WorkflowDef.prototype.setSchemaVersion = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional bool restartable = 9;
 * @return {boolean}
 */
proto.conductor.proto.WorkflowDef.prototype.getRestartable = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.conductor.proto.WorkflowDef} returns this
 */
proto.conductor.proto.WorkflowDef.prototype.setRestartable = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};


/**
 * optional bool workflow_status_listener_enabled = 10;
 * @return {boolean}
 */
proto.conductor.proto.WorkflowDef.prototype.getWorkflowStatusListenerEnabled = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 10, false));
};


/**
 * @param {boolean} value
 * @return {!proto.conductor.proto.WorkflowDef} returns this
 */
proto.conductor.proto.WorkflowDef.prototype.setWorkflowStatusListenerEnabled = function(value) {
  return jspb.Message.setProto3BooleanField(this, 10, value);
};


/**
 * optional string owner_email = 11;
 * @return {string}
 */
proto.conductor.proto.WorkflowDef.prototype.getOwnerEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.conductor.proto.WorkflowDef} returns this
 */
proto.conductor.proto.WorkflowDef.prototype.setOwnerEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional TimeoutPolicy timeout_policy = 12;
 * @return {!proto.conductor.proto.WorkflowDef.TimeoutPolicy}
 */
proto.conductor.proto.WorkflowDef.prototype.getTimeoutPolicy = function() {
  return /** @type {!proto.conductor.proto.WorkflowDef.TimeoutPolicy} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {!proto.conductor.proto.WorkflowDef.TimeoutPolicy} value
 * @return {!proto.conductor.proto.WorkflowDef} returns this
 */
proto.conductor.proto.WorkflowDef.prototype.setTimeoutPolicy = function(value) {
  return jspb.Message.setProto3EnumField(this, 12, value);
};


/**
 * optional int64 timeout_seconds = 13;
 * @return {number}
 */
proto.conductor.proto.WorkflowDef.prototype.getTimeoutSeconds = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.conductor.proto.WorkflowDef} returns this
 */
proto.conductor.proto.WorkflowDef.prototype.setTimeoutSeconds = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * map<string, google.protobuf.Value> variables = 14;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.google.protobuf.Value>}
 */
proto.conductor.proto.WorkflowDef.prototype.getVariablesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.google.protobuf.Value>} */ (
      jspb.Message.getMapField(this, 14, opt_noLazyCreate,
      proto.google.protobuf.Value));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.conductor.proto.WorkflowDef} returns this
 */
proto.conductor.proto.WorkflowDef.prototype.clearVariablesMap = function() {
  this.getVariablesMap().clear();
  return this;};


/**
 * map<string, google.protobuf.Value> input_template = 15;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.google.protobuf.Value>}
 */
proto.conductor.proto.WorkflowDef.prototype.getInputTemplateMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.google.protobuf.Value>} */ (
      jspb.Message.getMapField(this, 15, opt_noLazyCreate,
      proto.google.protobuf.Value));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.conductor.proto.WorkflowDef} returns this
 */
proto.conductor.proto.WorkflowDef.prototype.clearInputTemplateMap = function() {
  this.getInputTemplateMap().clear();
  return this;};


goog.object.extend(exports, proto.conductor.proto);
